apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: openspeedtest-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-operationtimecapsule
  data: []
  dataFrom:
    - extract:
        key: apps/openspeedtest
