---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: navidrome-music
spec:
  capacity:
    storage: 10Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - vers=3.1.1
    - hard
    - uid=4533
    - gid=3144
    - file_mode=0440
    - dir_mode=0550
  csi:
    driver: smb.csi.k8s.io
    readOnly: true
    volumeHandle: navidrome-music
    volumeAttributes:
      source: "//gringotts/timecapsule/Media/Music"
    nodeStageSecretRef:
      name: navidrome-smb-secret
      namespace: temple-of-time
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: navidrome-music
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Ti
  volumeName: navidrome-music
