apiVersion: v1
kind: ConfigMap
metadata:
  name: crowdsec-acquis-gitlab
data:
  90-gitlab-loki.yaml: |
    source: loki
    url: http://loki.gossip-stone.svc.cluster.local:3100
    limit: 1000
    query: |
      {namespace="hyrule-castle", container="webservice"} |~ "/users/sign_in|ldapmain/callback"
    labels:
      type: gitlab
    wait_for_ready: 10s
