apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-hubzilla-to-hubzilla-mariadb
spec:
  selector:
    matchLabels:
      app: hubzilla-mariadb
  action: ALLOW
  rules:
    - from:
        - source:
            principals:
              - cluster.local/ns/temple-of-time/sa/hubzilla
      to:
        - operation:
            ports: ["3306"]
