apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-ghost-to-ghost-mysql
spec:
  selector:
    matchLabels:
      app: ghost-mysql
  action: ALLOW
  rules:
    - from:
        - source:
            principals:
              - cluster.local/ns/temple-of-time/sa/ghost
      to:
        - operation:
            ports: ["3306"]
