apiVersion: v1
kind: Secret
metadata:
    name: velero-minio-credentials
    namespace: kube-system
type: Opaque
stringData:
    cloud: ENC[AES256_GCM,data:JFCj7IFMeM+3KILZQ3TLCpaDx6k68n6GH71H5CAhAGlg1w2dqm4wsgxWf1gzK7yzPtiJ8bsLFUANME9drsOeOSDITwUIZybIc2Csl0YPi03G6/G8ca3rU6ezxTyLR9zP3x9U2w==,iv:4t/IM8lB4uTJg8udmRBjUG/BO/CtLUPtujKjccKuF34=,tag:H1T5QQnAzYBxE4LYLIaIqw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6UnZiNTIrcUFIUENrczNl
            cklRTktqYnBjbDJKSTRYNEZWK0xoN3FJeUJJClc1UUJWelZMZzk2YWdFTzJnK3JT
            SmY5bnZoUE0xMUZkTzFldU1yQTdObXMKLS0tIEsvUUhLbHNoRXVKOWt3RkQyVWEr
            alA0d3o2WFN3dndwR2JlZys3NXQzVDQK0O8n9yW2jLtRCDAe8l6SVNydplz8yRTJ
            H+BRZ7lW06XWtbqBKMcFo8si/ZWVspL9h1jzMD9tqM4iMufDt4QG+g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1y8vegwlhcdgerrtn5947j5lcsswcu0zz6ukhs0hvvhsp79sa99nsn82dkr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-07T21:43:51Z"
    mac: ENC[AES256_GCM,data:042TiPHckME7DRfNcmOwDmf5qkUdAPghwiZBMyqJbVadVRfNj0KwovmpCq6GyrCsOZmltD5qMzlDzPuIUOyJc52wNONMnrQnjTgUVygLT0y/t5g2wTgMXxjnEuv73wG2nj3Tuhxf5zyalj6vq1s9TKS1SzGznJxzwlPneYYQckI=,iv:y3dScIy4DQBtkK+Me0jNLGS9OiinRgD2T3xa70Ma1EA=,tag:o+vNzwkqcMwKVJY+RoiYtw==,type:str]
    version: 3.13.3
