apiVersion: v1
kind: Secret
metadata:
    name: velero-legacy-credentials
    namespace: kube-system
type: Opaque
stringData:
    cloud: ENC[AES256_GCM,data:LQtvwmy2EYZUO4tLTTvoXQOFTaUn64LyQPhWVf8nxe2GTcsSVUieuS6wGneLhlIYnGduCYf89OLE/z2b+8++Ju9CTCRCtNDfpn98FMahSGXPkwBVQKuw5pb2aEreJ05mFELMzV9q2TeFkEr55JJy6w==,iv:puGQz/jH1y6dPyHQic8XQnCLU+aJKUwY0gLm5tEAmzU=,tag:WKkjWKh0ILVG7RKCXhhFwQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y8vegwlhcdgerrtn5947j5lcsswcu0zz6ukhs0hvvhsp79sa99nsn82dkr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0TzRhMDBUek5qSFg3MTlU
            M2NNL0o3K3EwczVPSnczdmRMOWM5dWl5MXdNCjZkY0Q1UzlWS3JoWmFUWklzejdL
            VGZSS3ZGN2Fsd01OUlFqeGtnRjRMRVUKLS0tIEYyaVdpazgrWlFNV2tMZkpIVTR5
            eGlKcENHSEtPWVdDUFY2MGpCU2o1bVUKIspGax8MgWhbn66gK/k4fTxB/UcE7y3t
            iLSm1WQP6qOkgxMtqaxCKBIbV9jKLQyEpRC9+31Ltc44Eqgg6IWL+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-19T08:42:45Z"
    mac: ENC[AES256_GCM,data:/BrKuH2ll5y1RmQjLaCO6vavCt/MzGZk2ckumfMg1/mn2tmxRIQnfVbFB+ir7GNli24oB1lJ9jWZv3fwv3OHsdAKZeoV9n9xcmINUSHpz+8bvc38uWRVHhUA81N2JddbBB1mNPhFhQDk7SFDb7QmOKymSx3U0V7f1xWVOJQ97aE=,iv:23YY5NlSiFZmUtMdynhVBiwyPPHfncPp+NryQlkvk8I=,tag:8KO5aGrlECMEQSjanwhokw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
