apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-graphite-exporter-truenas-lan
spec:
  description: >-
    LAN-only ingress to graphite-exporter-truenas (172.22.30.137) on 2003/TCP.
  enableDefaultDeny:
    ingress: false
    egress: false
  endpointSelector:
    matchLabels:
      app: graphite-exporter-truenas
  ingress:
    - fromCIDRSet:
        - cidr: "10.0.0.0/8"
        - cidr: "172.16.0.0/12"
        - cidr: "192.168.0.0/16"
          except:
            - "192.168.144.0/20"
      toPorts:
        - ports:
            - port: "2003"
              protocol: TCP
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-nutify-lan
spec:
  description: >-
    LAN-only ingress to nutify (172.22.30.137) on 3493,5050,443/TCP.
  enableDefaultDeny:
    ingress: false
    egress: false
  endpointSelector:
    matchLabels:
      app: nutify
  ingress:
    - fromCIDRSet:
        - cidr: "10.0.0.0/8"
        - cidr: "172.16.0.0/12"
        - cidr: "192.168.0.0/16"
          except:
            - "192.168.144.0/20"
      toPorts:
        - ports:
            - port: "3493"
              protocol: TCP
            - port: "5050"
              protocol: TCP
            - port: "443"
              protocol: TCP
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-prometheus-exporter-eaton-ups-lan
spec:
  description: >-
    LAN-only ingress to prometheus-exporter-eaton-ups (172.22.30.137) on 9795/TCP.
  enableDefaultDeny:
    ingress: false
    egress: false
  endpointSelector:
    matchLabels:
      app: prometheus-exporter-eaton-ups
  ingress:
    - fromCIDRSet:
        - cidr: "10.0.0.0/8"
        - cidr: "172.16.0.0/12"
        - cidr: "192.168.0.0/16"
          except:
            - "192.168.144.0/20"
      toPorts:
        - ports:
            - port: "9795"
              protocol: TCP
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-prometheus-exporter-pve-lan
spec:
  description: >-
    LAN-only ingress to prometheus-exporter-pve (172.22.30.137) on 9221/TCP.
  enableDefaultDeny:
    ingress: false
    egress: false
  endpointSelector:
    matchLabels:
      app: prometheus-exporter-pve
  ingress:
    - fromCIDRSet:
        - cidr: "10.0.0.0/8"
        - cidr: "172.16.0.0/12"
        - cidr: "192.168.0.0/16"
          except:
            - "192.168.144.0/20"
      toPorts:
        - ports:
            - port: "9221"
              protocol: TCP
