apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bulkvs-ddns-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: PLACEHOLDER_SECRET_STORE
  target:
    name: bulkvs-ddns-secrets
  data:
    - secretKey: BULKVS_API_KEY
      remoteRef:
        key: PLACEHOLDER_VAULT_PATH
        property: BULKVS_API_KEY
