apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-loki-intra-cluster
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: loki
  action: ALLOW
  rules:
    - from:
        - source:
            principals:
              - cluster.local/ns/gossip-stone/sa/loki
      to:
        - operation:
            ports: ["3100", "7946", "9095"]
