apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-vmauth-to-vmselect
spec:
  selector:
    matchLabels:
      app: vmselect
  action: ALLOW
  rules:
    - from:
        - source:
            principals:
              - cluster.local/ns/gossip-stone/sa/vmauth
      to:
        - operation:
            ports: ["8481"]
