apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: romm-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao-operationtimecapsule
    kind: ClusterSecretStore
  target:
    name: romm-secrets
    creationPolicy: Owner
  data:
    - secretKey: db-user
      remoteRef:
        key: apps/romm
        property: MARIADB_USER
    - secretKey: db-password
      remoteRef:
        key: apps/romm
        property: MARIADB_PASSWORD
    - secretKey: mysql-root-password
      remoteRef:
        key: apps/romm
        property: MARIADB_ROOT_PASSWORD
    - secretKey: auth-secret-key
      remoteRef:
        key: apps/romm
        property: AUTH_SECRET_KEY
    - secretKey: smb-username
      remoteRef:
        key: apps/romm
        property: SAMBA_USERNAME
    - secretKey: smb-password
      remoteRef:
        key: apps/romm
        property: SAMBA_PASSWORD
    - secretKey: oidc-client-id
      remoteRef:
        key: apps/romm
        property: OIDC_CLIENT_ID
    - secretKey: oidc-client-secret
      remoteRef:
        key: apps/romm
        property: OIDC_CLIENT_SECRET
