apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: romm
spec:
  replicas: 1
  template:
    metadata:
      labels:
        policy.prplanit.com/ingress: "true"
        policy.prplanit.com/cap.oidc: "true"
    spec:
      containers:
        - name: romm
          image: docker.io/rommapp/romm:5.3.1
          env:
            - name: OIDC_ENABLED
              value: "true"
            - name: OIDC_PROVIDER
              value: "Zitadel"
            - name: OIDC_SERVER_APPLICATION_URL
              value: "https://sso.prplanit.com"
            - name: OIDC_SERVER_METADATA_URL
              value: "https://sso.prplanit.com/.well-known/openid-configuration"
            - name: OIDC_USERNAME_ATTRIBUTE
              value: "preferred_username"
            - name: OIDC_AUTOLOGIN
              value: "false"
            - name: OIDC_ALLOW_REGISTRATION
              value: "true"
            - name: OIDC_RP_INITIATED_LOGOUT
              value: "false"
            - name: OIDC_END_SESSION_ENDPOINT
              value: ""
            - name: OIDC_REDIRECT_URI
              value: "https://romm.pcfae.com/api/oauth/openid"
            - name: OIDC_CLAIM_ROLES
              value: "roles"
            - name: OIDC_ROLE_ADMIN
              value: "operator"
            - name: OIDC_ROLE_EDITOR
              value: "admin"
            - name: OIDC_ROLE_VIEWER
              value: "trusted"
            - name: OIDC_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: romm-secrets
                  key: oidc-client-id
            - name: OIDC_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: romm-secrets
                  key: oidc-client-secret
  volumeClaimTemplates:
    - metadata:
        name: shooting-gallery-romm-resources
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: ceph-rbd-retain
        resources:
          requests:
            storage: 10Gi
    - metadata:
        name: shooting-gallery-romm-redis
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: ceph-rbd-retain
        resources:
          requests:
            storage: 5Gi
    - metadata:
        name: shooting-gallery-romm-assets
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: ceph-rbd-retain
        resources:
          requests:
            storage: 10Gi
    - metadata:
        name: shooting-gallery-romm-config
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: ceph-rbd-retain
        resources:
          requests:
            storage: 1Gi
