apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hyrule-castle
resources:
  - cnp-default-deny-ingress.yaml
  - cnp-cell-membrane-gateway.yaml
  - cnp-apt-cacher-ng.yaml
  - cnp-galera-replication.yaml
  - cnp-gitlab-webhooks.yaml
