apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hyrule-castle
resources:
  - cnp-default-deny-ingress.yaml
  - cnp-cell-membrane-gateway.yaml
  - cnp-cell-membrane-oidc-consumers.yaml
  - cnp-cell-membrane-monitoring.yaml
  - cnp-apt-cacher-ng.yaml
  - cnp-egress-apt-cacher-ng.yaml
  - cnp-egress-cell-membrane-gateway.yaml
  - cnp-egress-external-apps.yaml
  - cnp-egress-to-gateway.yaml
  - cnp-galera-replication.yaml
  - cnp-gitlab-webhooks.yaml
  - cnp-harbor.yaml
