{
 "title": "Loki-Canary",
 "description": "Loki Canary is a standalone app that audits the log capturing performance of Loki.",
 "tags": [
  "loki",
  "loki-canary",
  "managed",
  "managed"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Loki logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Loki logs",
   "type": "logs",
   "description": "anything except \"ppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp\"",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "{app=\"loki\",container=\"loki\"} !=\"ppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp\" !~ \"info\""
    }
   ]
  },
  { "title": "Missing entries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Missing entries rate",
   "type": "timeseries",
   "description": "counts log entries not received within the maxWait duration via both websocket and direct query",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(loki_canary_missing_entries_total[$__rate_interval]))",
     "legendFormat": "rate"
    }
   ]
  },
  {
   "title": "Unexpected entries rate",
   "type": "timeseries",
   "description": "counts a log entry received which was not expected (e.g. received after reported missing)",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(loki_canary_unexpected_entries_total[$__rate_interval]))",
     "legendFormat": "rate"
    }
   ]
  },
  {
   "title": "Out of order entries rate",
   "type": "timeseries",
   "description": "counts log entries received with a timestamp more recent than the others in the queue",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(loki_canary_out_of_order_entries_total[$__rate_interval]))",
     "legendFormat": "rate"
    }
   ]
  },
  {
   "title": "Total entries rate",
   "type": "timeseries",
   "description": "counts log entries written to the file",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(loki_canary_entries_total[$__rate_interval]))",
     "legendFormat": "rate"
    }
   ]
  },
  {
   "title": "Duplicate entries rate",
   "type": "timeseries",
   "description": "counts a log entry received more than one time",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(loki_canary_duplicate_entries_total[$__rate_interval]))",
     "legendFormat": "rate"
    }
   ]
  },
  {
   "title": "Total spots rate",
   "type": "timeseries",
   "description": "total count of entries spot checked",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(loki_canary_spot_check_entries_total[$__rate_interval]))",
     "legendFormat": "rate"
    }
   ]
  },
  {
   "title": "Total spots missing rate",
   "type": "timeseries",
   "description": "log entries not received when directly queried as part of spot checking",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum(rate(loki_canary_spot_check_missing_entries_total[$__rate_interval]))",
     "legendFormat": "rate"
    }
   ]
  },
  {
   "title": "Average response latency [1m]",
   "type": "timeseries",
   "description": "is how long it takes for log lines to be returned from Loki in seconds.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "sum(rate(loki_canary_response_latency_seconds_sum[$__rate_interval])) / sum(rate(loki_canary_response_latency_seconds_count[$__rate_interval]))",
     "legendFormat": "avg"
    },
    {
     "expr": "sum(rate(loki_canary_response_latency_seconds_bucket{le=\"0.5\"}[$__rate_interval]))",
     "legendFormat": "le=0.5"
    },
    {
     "expr": "sum(rate(loki_canary_response_latency_seconds_bucket{le=\"1\"}[$__rate_interval]))",
     "legendFormat": "le=1"
    },
    {
     "expr": "sum(rate(loki_canary_response_latency_seconds_bucket{le=\"2\"}[$__rate_interval]))",
     "legendFormat": "le=2"
    },
    {
     "expr": "sum(rate(loki_canary_response_latency_seconds_bucket{le=\"4\"}[$__rate_interval]))",
     "legendFormat": "le=4"
    },
    {
     "expr": "sum(rate(loki_canary_response_latency_seconds_bucket{le=\"8\"}[$__rate_interval]))",
     "legendFormat": "le=8"
    },
    {
     "expr": "sum(rate(loki_canary_response_latency_seconds_bucket{le=\"16\"}[$__rate_interval]))",
     "legendFormat": "le=16"
    },
    {
     "expr": "sum(rate(loki_canary_response_latency_seconds_bucket{le=\"32\"}[$__rate_interval]))",
     "legendFormat": "le=32"
    },
    {
     "expr": "sum(rate(loki_canary_response_latency_seconds_bucket{le=\"64\"}[$__rate_interval]))",
     "legendFormat": "le=64"
    },
    {
     "expr": "sum(rate(loki_canary_response_latency_seconds_bucket{le=\"128\"}[$__rate_interval]))",
     "legendFormat": "le=128"
    },
    {
     "expr": "sum(rate(loki_canary_response_latency_seconds_bucket{le=\"256\"}[$__rate_interval]))",
     "legendFormat": "le=256"
    },
    {
     "expr": "sum(rate(loki_canary_response_latency_seconds_bucket{le=\"+Inf\"}[$__rate_interval]))",
     "legendFormat": "le=+Inf"
    }
   ]
  },
  {
   "title": "Metric test diff",
   "type": "timeseries",
   "description": "difference between expected and actual metric count, this should be something around 5*number_of_loki_canary_instances",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum(loki_canary_metric_test_expected) - sum(loki_canary_metric_test_actual)",
     "legendFormat": "difference"
    }
   ]
  },
  {
   "title": "Metric test expected, actual",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "sum(loki_canary_metric_test_expected)",
     "legendFormat": "expected"
    },
    {
     "expr": "sum(loki_canary_metric_test_actual)",
     "legendFormat": "actual"
    }
   ]
  },
  { "title": "Websocket", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Websocket missing entries rate",
   "type": "timeseries",
   "description": "counts log entries not received within the wait duration via the websocket connection",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "sum(rate(loki_canary_websocket_missing_entries_total[$__rate_interval]))",
     "legendFormat": "rate"
    }
   ]
  },
  {
   "title": "Websocket reconnects rate",
   "type": "timeseries",
   "description": "counts every time the websocket connection has to reconnect",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 39 },
   "targets": [
    {
     "expr": "sum(rate(loki_canary_ws_reconnects_total[$__rate_interval]))",
     "legendFormat": "rate"
    }
   ]
  },
  {
   "title": "Websocket pings rate",
   "type": "timeseries",
   "description": "every time the websocket receives a ping message",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 39 },
   "targets": [
    {
     "expr": "sum(rate(loki_canary_ws_pings_total[$__rate_interval]))",
     "legendFormat": "rate"
    }
   ]
  }
 ]
}