apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bank-vaults-operator
spec:
  chart:
    spec:
      # renovate: datasource=docker depName=ghcr.io/bank-vaults/helm-charts/vault-operator
      version: "1.23.0"
  values:
    # Prometheus scraping
    podAnnotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "8383"
    image:
      # renovate: datasource=docker depName=ghcr.io/bank-vaults/vault-operator
      tag: v1.23.0
    bankVaults:
      image:
        # renovate: datasource=docker depName=ghcr.io/bank-vaults/bank-vaults
        tag: v1.32.0
    webhook:
      image:
        # renovate: datasource=docker depName=ghcr.io/bank-vaults/vault-secrets-webhook
        tag: v1.22.1
