apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: navidrome
  annotations:
    gatus.home-operations.com/endpoint: |
      group: "Public Apps (Temple of Time🕰️)"
      conditions:
        - "[STATUS] == any(200, 302)"
        - "[RESPONSE_TIME] < 5000"
spec:
  parentRefs:
    - name: cell-membrane-gateway
      namespace: hyrule-castle
  hostnames:
    - "music.optcp.com"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: navidrome
          port: 8080
