apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: opnform-postgres
spec:
  template:
    metadata:
      labels:
        policy.prplanit.com/access-class: postgres
        policy.prplanit.com/service-scope: hyrule-castle.opnform.postgres
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: ceph-rbd
        resources:
          requests:
            storage: 20Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: opnform-redis
spec:
  template:
    metadata:
      labels:
        policy.prplanit.com/access-class: redis
        policy.prplanit.com/service-scope: hyrule-castle.opnform.redis
  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: ceph-rbd
        resources:
          requests:
            storage: 10Gi
