apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-tactical-nginx-to-tactical-frontend
spec:
  selector:
    matchLabels:
      app: tactical-frontend
  action: ALLOW
  rules:
    - from:
        - source:
            principals:
              - cluster.local/ns/hookshot/sa/tactical-nginx
      to:
        - operation:
            ports: ["8080"]
