apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-tactical-nginx-to-tactical-meshcentral
spec:
  selector:
    matchLabels:
      app: tactical-meshcentral
  action: ALLOW
  rules:
    - from:
        - source:
            principals:
              - cluster.local/ns/hookshot/sa/tactical-nginx
              - cluster.local/ns/hookshot/sa/tactical-backend
      to:
        - operation:
            ports: ["4443"]
