apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-netbird-coturn-lan
spec:
  description: >-
    LAN-only ingress to netbird-coturn (172.22.30.86) on
    3478/UDP, 3478/TCP, 5349/TCP.
  enableDefaultDeny:
    ingress: false
    egress: false
  endpointSelector:
    matchLabels:
      app: netbird-coturn
  ingress:
    - fromCIDRSet:
        - cidr: "10.0.0.0/8"
        - cidr: "172.16.0.0/12"
          except:
            - "192.168.144.0/20"
        - cidr: "192.168.0.0/16"
          except:
            - "192.168.144.0/20"
      toPorts:
        - ports:
            - port: "3478"
              protocol: UDP
            - port: "3478"
              protocol: TCP
            - port: "5349"
              protocol: TCP
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-unifi-app-lan
spec:
  description: >-
    LAN-only ingress to unifi-app (172.22.30.20) on
    8443,8080,8843,8880,6789/TCP, 3478,10001,1900/UDP, 5514/UDP.
  enableDefaultDeny:
    ingress: false
    egress: false
  endpointSelector:
    matchLabels:
      app: unifi-app
  ingress:
    - fromCIDRSet:
        - cidr: "10.0.0.0/8"
        - cidr: "172.16.0.0/12"
          except:
            - "192.168.144.0/20"
        - cidr: "192.168.0.0/16"
          except:
            - "192.168.144.0/20"
      toPorts:
        - ports:
            - port: "8443"
              protocol: TCP
            - port: "3478"
              protocol: UDP
            - port: "10001"
              protocol: UDP
            - port: "8080"
              protocol: TCP
            - port: "1900"
              protocol: UDP
            - port: "8843"
              protocol: TCP
            - port: "8880"
              protocol: TCP
            - port: "6789"
              protocol: TCP
            - port: "5514"
              protocol: UDP
