apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: zeldas-lullaby
resources:
  - cnp-default-deny-ingress.yaml
  - cnp-loadbalancers.yaml
  - cnp-webhooks.yaml
  - cnp-vault.yaml
  - cnp-zitadel-internal.yaml
