apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bulkvs-ip-sync-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-zeldas-letter
  data: []
  dataFrom:
    - extract:
        key: apps/bulkvs-ip-sync
