apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homarr-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-precisionplanit
    kind: ClusterSecretStore
  target:
    name: homarr-secrets
    creationPolicy: Owner
  data:
    - secretKey: SECRET_ENCRYPTION_KEY
      remoteRef:
        key: apps/homarr
        property: SECRET_ENCRYPTION_KEY
    - secretKey: AUTH_OIDC_CLIENT_ID
      remoteRef:
        key: apps/homarr
        property: OIDC_CLIENT_ID
    - secretKey: AUTH_OIDC_CLIENT_SECRET
      remoteRef:
        key: apps/homarr
        property: OIDC_CLIENT_SECRET
    - secretKey: AUTH_SECRET
      remoteRef:
        key: apps/homarr
        property: AUTH_SECRET
