apiVersion: apps/v1
kind: Deployment
metadata:
  name: matrix-element
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: element
          image: ghcr.io/element-hq/element-web:v1.12.27
