apiVersion: v1
kind: ServiceAccount
metadata:
  name: boundary-controller
  labels:
    app.kubernetes.io/name: boundary
    app.kubernetes.io/component: controller
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: boundary-worker
  labels:
    app.kubernetes.io/name: boundary
    app.kubernetes.io/component: worker
