apiVersion: v1
kind: Service
metadata:
  name: boundary-worker
  labels:
    app.kubernetes.io/name: boundary
    app.kubernetes.io/component: worker
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: boundary
    app.kubernetes.io/component: worker
  ports:
    - name: proxy
      port: 9202
      targetPort: proxy
      protocol: TCP
