apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitlab-root
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao-precisionplanit
    kind: ClusterSecretStore
  target:
    name: gitlab-initial-root-password
    creationPolicy: Owner
  data:
  - secretKey: password
    remoteRef:
      key: apps/gitlab
      property: root_password
