apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-monica-to-monica-db
spec:
  description: >-
    Allow monica app to access monica-db MariaDB on 3306/TCP.
  enableDefaultDeny:
    ingress: false
    egress: false
  endpointSelector:
    matchLabels:
      app: monica-db
  ingress:
    - fromEndpoints:
        - matchLabels:
            app: monica
      toPorts:
        - ports:
            - port: "3306"
              protocol: TCP
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-photoprism-x-to-mariadb
spec:
  description: >-
    Allow photoprism-x app to access photoprism-x-mariadb on 3306/TCP.
  enableDefaultDeny:
    ingress: false
    egress: false
  endpointSelector:
    matchLabels:
      app: photoprism-x-mariadb
  ingress:
    - fromEndpoints:
        - matchLabels:
            app: photoprism-x
      toPorts:
        - ports:
            - port: "3306"
              protocol: TCP
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-roundcube-primary-gmail-to-db
spec:
  description: >-
    Allow roundcube-primary-gmail app to access
    roundcube-primary-gmail-db on 3306/TCP.
  enableDefaultDeny:
    ingress: false
    egress: false
  endpointSelector:
    matchLabels:
      app: roundcube-primary-gmail-db
  ingress:
    - fromEndpoints:
        - matchLabels:
            app: roundcube-primary-gmail
      toPorts:
        - ports:
            - port: "3306"
              protocol: TCP
