apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: homebox-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-zeldas-letter
    kind: ClusterSecretStore
  target:
    name: homebox-secrets
    creationPolicy: Owner
  data:
    - secretKey: HBOX_AUTH_API_KEY_PEPPER
      remoteRef:
        key: apps/homebox
        property: HBOX_AUTH_API_KEY_PEPPER
