apiVersion: apps/v1
kind: Deployment
metadata:
  name: guacamole
spec:
  template:
    metadata:
      labels:
        policy.prplanit.com/ingress: "true"
        policy.prplanit.com/cap.postgres: "true"
        policy.prplanit.com/access-scope-postgres: hookshot.guacamole.postgres
    spec:
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
      initContainers:
        - name: generate-initdb
          image: docker.io/guacamole/guacamole@sha256:f5a2e47965e48e0acc27d0610221b5abb6c03bab29b21558d9fc199c712c75da
        - name: init-db
          image: docker.io/postgres:15-alpine
      containers:
        - name: guacamole
          image: docker.io/guacamole/guacamole@sha256:f5a2e47965e48e0acc27d0610221b5abb6c03bab29b21558d9fc199c712c75da
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "2Gi"
