apiVersion: apps/v1
kind: Deployment
metadata:
  name: harbor-proxy-cache-proxy
  labels:
    app: harbor-proxy-cache-proxy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: harbor-proxy-cache-proxy
  template:
    metadata:
      labels:
        app: harbor-proxy-cache-proxy
        policy.prplanit.com/ingress: "true"
    spec:
      serviceAccountName: harbor-proxy-cache-proxy
      containers:
        - name: openresty
          image: docker.io/openresty/openresty:1.27.1.2-alpine
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /usr/local/openresty/nginx/conf/nginx.conf
              subPath: nginx.conf
              readOnly: true
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              memory: 128Mi
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 5
      volumes:
        - name: config
          configMap:
            name: harbor-proxy-cache-nginx
