apiVersion: v1
kind: Service
metadata:
  name: harbor-proxy-cache-proxy
  labels:
    app: harbor-proxy-cache-proxy
spec:
  selector:
    app: harbor-proxy-cache-proxy
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
