apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: wazuh-manager-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: PLACEHOLDER_SECRET_STORE
  target:
    name: wazuh-manager-secrets
    template:
      engineVersion: v2
      data:
        INDEXER_URL: "{{ .INDEXER_URL }}"
        INDEXER_USERNAME: "{{ .INDEXER_USERNAME }}"
        INDEXER_PASSWORD: "{{ .INDEXER_PASSWORD }}"
        FILEBEAT_SSL_VERIFICATION_MODE: "{{ .FILEBEAT_SSL_VERIFICATION_MODE }}"
        SSL_CERTIFICATE_AUTHORITIES: "/etc/ssl/wazuh/ca.crt"
        SSL_CERTIFICATE: "/etc/ssl/wazuh/tls.crt"
        SSL_KEY: "/etc/ssl/wazuh/tls.key"
        API_USERNAME: "{{ .API_USERNAME }}"
        API_PASSWORD: "{{ .API_PASSWORD }}"
  dataFrom:
    - extract:
        key: PLACEHOLDER_VAULT_PATH
