apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: twenty-redis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        policy.prplanit.com/access-class: redis
        policy.prplanit.com/service-scope: hyrule-castle.twenty.redis
    spec:
      serviceAccountName: twenty
      securityContext:
        runAsUser: 999
        runAsGroup: 1000
        fsGroup: 1000
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      imagePullSecrets:
        - name: cr-pcfae-admin-pull-secret
      containers:
        - name: redis
          image: docker.io/redis:8.10.1-alpine
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
  volumeClaimTemplates:
    - metadata:
        name: hyrule-castle-twenty-redis
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: ceph-rbd-retain
        resources:
          requests:
            storage: 5Gi
