apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-neko-gateway-lan
spec:
  description: >-
    LAN-only TURN/STUN ingress to neko-gateway (172.22.30.120).
  enableDefaultDeny:
    ingress: false
    egress: false
  endpointSelector:
    matchLabels:
      app: neko-gateway
  ingress:
    - fromCIDRSet:
        - cidr: "10.0.0.0/8"
        - cidr: "172.16.0.0/12"
          except:
            - "172.22.144.0/24"
        - cidr: "192.168.0.0/16"
          except:
            - "192.168.144.0/20"
      toPorts:
        - ports:
            - port: "3478"
              protocol: UDP
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-py-kms-lan
spec:
  description: >-
    LAN-only KMS ingress to py-kms (172.22.30.33) on port 1688.
  enableDefaultDeny:
    ingress: false
    egress: false
  endpointSelector:
    matchLabels:
      app: py-kms
  ingress:
    - fromCIDRSet:
        - cidr: "10.0.0.0/8"
        - cidr: "172.16.0.0/12"
          except:
            - "172.22.144.0/24"
        - cidr: "192.168.0.0/16"
          except:
            - "192.168.144.0/20"
      toPorts:
        - ports:
            - port: "1688"
              protocol: TCP
