apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: swift-sail
resources:
  - cnp-arr-mesh.yaml
  - cnp-default-deny-ingress.yaml
  - cnp-gatus-probes.yaml
  - cnp-loadbalancers.yaml
