apiVersion: apps/v1
kind: Deployment
metadata:
  name: frappe-suite-scheduler
spec:
  template:
    spec:
      containers:
        - name: scheduler
          image: docker.io/hlhd/frappe-suite:v16.33.0
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "10m"
              memory: "64Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
      volumes:
        - name: sites-data
          persistentVolumeClaim:
            claimName: hyrule-castle-frappe-suite-sites
        - name: logs-data
          persistentVolumeClaim:
            claimName: hyrule-castle-frappe-suite-logs
