apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: boundary-kms-keys
spec:
  refreshInterval: "0"
  secretStoreRef:
    name: vault-zeldas-letter
    kind: ClusterSecretStore
  target:
    name: boundary-kms-keys
    creationPolicy: Owner
  data:
    - secretKey: KMS_ROOT_KEY
      remoteRef:
        key: apps/boundary
        property: KMS_ROOT_KEY
    - secretKey: KMS_WORKER_AUTH_KEY
      remoteRef:
        key: apps/boundary
        property: KMS_WORKER_AUTH_KEY
    - secretKey: KMS_RECOVERY_KEY
      remoteRef:
        key: apps/boundary
        property: KMS_RECOVERY_KEY
