apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: boundary-conn-string
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-zeldas-letter
    kind: ClusterSecretStore
  target:
    name: boundary-conn-string
    creationPolicy: Owner
    template:
      data:
        BOUNDARY_PG_URL: "postgresql://boundary:{{ .password }}@boundary-postgres-rw.hookshot.svc.cluster.local:5432/boundary?sslmode=require"
  data:
    - secretKey: password
      remoteRef:
        key: apps/boundary
        property: POSTGRES_PASSWORD
