apiVersion: apps/v1
kind: Deployment
metadata:
  name: boundary-worker
spec:
  replicas: 2
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: boundary
              app.kubernetes.io/component: worker
      initContainers:
        - name: render-config
          image: docker.io/hashicorp/boundary:0.21.1
      containers:
        - name: boundary
          image: docker.io/hashicorp/boundary:0.21.1
