apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-endlessh-go-loadbalancer
spec:
  selector:
    matchLabels:
      app: endlessh-go
  action: ALLOW
  rules:
    # SSH honeypot — must accept internet attackers
    - to:
        - operation:
            ports: ["2222", "2112"]
