apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-home-assistant-to-piper
spec:
  selector:
    matchLabels:
      app: piper
  action: ALLOW
  rules:
    - from:
        - source:
            principals:
              - cluster.local/ns/lens-of-truth/sa/home-assistant
      to:
        - operation:
            ports: ["10200"]
