apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: arylls-lookout
resources:
  - ../../../../base/istio-policies
  - allow-gateway-ingress-xylem.yaml
  - allow-intra-breakglass.yaml
  - allow-xylem-gateway-loadbalancer.yaml
