apiVersion: v1
kind: Service
metadata:
  name: matrix-synapse
  labels:
    app: matrix-synapse
spec:
  selector:
    app: matrix-synapse
  ports:
    - port: 8008
      targetPort: http
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: matrix-auth
  labels:
    app: matrix-auth
spec:
  selector:
    app: matrix-auth
  ports:
    - port: 8080
      targetPort: http
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: matrix-element
  labels:
    app: matrix-element
spec:
  selector:
    app: matrix-element
  ports:
    - port: 8080
      targetPort: http
      name: http
