apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-photoprism-x-to-photoprism-x-mariadb
spec:
  selector:
    matchLabels:
      app: photoprism-x-mariadb
  action: ALLOW
  rules:
    - from:
        - source:
            principals:
              - cluster.local/ns/pedestal-of-time/sa/photoprism-x
      to:
        - operation:
            ports: ["3306"]
