apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-plex-ms-x-loadbalancer
spec:
  selector:
    matchLabels:
      app: plex-ms-x
  action: ALLOW
  rules:
    - from:
        - source:
            ipBlocks:
              - "10.0.0.0/8"
              - "172.16.0.0/12"
              - "192.168.0.0/16"
            notIpBlocks:
              - "192.168.144.0/20"  # exclude pod CIDR
      to:
        - operation:
            ports: ["32400", "8324", "32469", "1900", "32410", "32412", "32413", "32414"]
