apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflare-ddns
spec:
  template:
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: cloudflare-ddns
          image: docker.io/favonia/cloudflare-ddns:1
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              cpu: 100m
              memory: 64Mi
          envFrom:
            - configMapRef:
                name: cloudflare-ddns-config
            - secretRef:
                name: cloudflare-ddns-secrets
