apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-ddns-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-zeldas-letter
  data: []
  dataFrom:
    - extract:
        key: apps/cloudflare-ddns
