apiVersion: apps/v1
kind: Deployment
metadata:
  name: yesimvegan-site
spec:
  template:
    metadata:
      labels:
        policy.prplanit.com/ingress: "true"
    spec:
      imagePullSecrets:
        - name: cr-pcfae-admin-pull-secret
      containers:
        - name: yesimvegan-site
          image: cr.pcfae.com/sofmeright/yesimvegan.com:v0.0.3
