apiVersion: v1
kind: ServiceAccount
metadata:
  name: frappe-suite-mariadb
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frappe-suite-redis-queue
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frappe-suite-sites
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frappe-suite-redis-cache
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frappe-suite-frontend
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frappe-suite-websocket
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frappe-suite-scheduler
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frappe-suite-queue-long
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frappe-suite-queue-short
