apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: frappe-suite-redis-queue
spec:
  revisionHistoryLimit: 5
  serviceName: frappe-suite-redis-queue
  replicas: 1
  selector:
    matchLabels:
      app: frappe-suite-redis-queue
  template:
    metadata:
      labels:
        app: frappe-suite-redis-queue
    spec:
      serviceAccountName: frappe-suite-redis-queue
      containers:
        - name: redis
          image: PLACEHOLDER_REDIS_IMAGE
          securityContext:
            capabilities:
              drop:
                - ALL
          ports:
            - containerPort: 6379
              name: redis
          volumeMounts:
            - name: PLACEHOLDER_REDIS_QUEUE_DATA
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: PLACEHOLDER_REDIS_QUEUE_DATA
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: PLACEHOLDER_STORAGE_CLASS
        resources:
          requests:
            storage: 5Gi
