apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: calibre-web-samba-secret
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: openbao-operationtimecapsule
    kind: ClusterSecretStore
  target:
    name: calibre-web-samba-secret
    template:
      type: Opaque
      data:
        username: "{{ .SAMBA_USERNAME | toString }}"
        password: "{{ .SAMBA_PASSWORD | toString }}"
  dataFrom:
    - extract:
        key: apps/calibre-web
