apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - restrict-default-sa.yaml
  - mutate-redis-sentinel-sa.yaml
  - mutate-stunner-gateway-sa.yaml
  - gate-breakglass-label.yaml
  - enforce-image-policy.yaml
  - mutate-redis-contract-labels.yaml
  - mutate-probe-on-ingress.yaml
  - audit-pod-hardening.yaml
  - mutate-pod-hardening.yaml
  - enforce-pod-hardening.yaml
  - exception-pod-hardening-no-privesc.yaml
  - exception-pod-hardening-non-root.yaml
  - exception-pod-hardening-ro-rootfs.yaml
  - mutate-velero-maintenance-hardening.yaml
  - mutate-vault-sidecar-hardening.yaml
  - mutate-smb-pv-mount-options.yaml
