apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: mutate-probe-on-ingress
spec:
  rules:
    - name: add-probe-label-when-ingress
      match:
        any:
          - resources:
              kinds: ["Pod"]
              namespaces:
                - arylls-lookout
                - compass
                - delivery-bag
                - fairy-bottle
                - gorons-bracelet
                - gossip-stone
                - hookshot
                - hyrule-castle
                - king-of-red-lions
                - kokiri-forest
                - lens-of-truth
                - lost-woods
                - pedestal-of-time
                - shooting-gallery
                - swift-sail
                - temple-of-time
                - tingle-tuner
                - wallmaster
                - zeldas-lullaby
      preconditions:
        all:
          - key: "{{ request.object.metadata.labels.\"policy.prplanit.com/ingress\" || '' }}"
            operator: Equals
            value: "true"
      mutate:
        patchStrategicMerge:
          metadata:
            labels:
              policy.prplanit.com/probe: "true"
