apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nas-s3-provisioner-credentials
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-zeldas-letter
  target:
    name: nas-s3-provisioner-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
  refreshInterval: 5m
  dataFrom:
    - extract:
        key: nas-s3/provisioner
        conversionStrategy: Default
        decodingStrategy: None
