apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: vaultwarden-postgres-store
spec:
  configuration:
    destinationPath: s3://prplanit/dungeon/cnpg/vaultwarden
    endpointURL: http://172.22.150.101:8333
