apiVersion: v1
kind: Service
metadata:
  name: home-assistant
spec:
  type: ClusterIP
  selector:
    app: home-assistant
  ports:
    - name: http
      port: 8123
      targetPort: http
      protocol: TCP
    - name: http-ws
      port: 8080
      targetPort: http-ws
      protocol: TCP
