apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: default-deny-ingress
spec:
  description: >-
    Default deny all ingress for king-of-red-lions. Allows are additive
    from CCNPs (DNS, probes, webhooks) and namespace-specific CNPs
    (istiod xDS, stunner internal).
  endpointSelector: {}
  ingress: []
