apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/istio
patches:
  # Set namespace for HelmReleases to flux-system
  - patch: |-
      - op: add
        path: /metadata/namespace
        value: flux-system
    target:
      kind: HelmRelease
  # Add webhook label to istiod pods for ccnp-allow-kube-apiserver-webhooks
  - patch: |-
      apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      metadata:
        name: istiod
      spec:
        values:
          pilot:
            podLabels:
              policy.prplanit.com/webhook: "true"
    target:
      kind: HelmRelease
      name: istiod
