---
# Patch login-v2-deployment with actual domain
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zitadel-login-v2
spec:
  template:
    spec:
      containers:
        - name: zitadel-login-v2
          env:
            - name: ZITADEL_ISSUER
              value: "https://sso.prplanit.com"
