---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zitadel
spec:
  template:
    spec:
      initContainers:
        - name: wait-for-setup
          image: docker.io/alpine/k8s:1.37.0
          command:
            - sh
            - -c
            - |
              echo "Waiting for setup job to complete..."
              until [ "$(kubectl get job zitadel-setup -n zeldas-lullaby -o jsonpath='{.status.succeeded}' 2>/dev/null)" = "1" ]; do
                echo "Setup job not complete yet, waiting..."
                sleep 5
              done
              echo "Setup job completed! Starting Zitadel..."
      containers:
        - name: zitadel
          image: ghcr.io/homelabhd/zitadel:dev-df4dbc1@sha256:18bf4c669116a9a8cdd5f902671268a16d4c0d9e8970857034490caee28c0883
