apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: zitadel-postgres-store
spec:
  configuration:
    destinationPath: s3://prplanit-dungeon-cnpg-zitadel
    endpointURL: http://172.22.150.101:8333
