apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-osticket-mariadb-galera
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: osticket-mariadb
  action: ALLOW
  rules:
    - from:
        - source:
            principals:
              - cluster.local/ns/hyrule-castle/sa/osticket-mariadb
      to:
        - operation:
            ports: ["3306", "4567", "4568", "4444"]
