apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-frappe-suite-frontend-to-frappe-suite-sites
spec:
  selector:
    matchLabels:
      app: frappe-suite-sites
  action: ALLOW
  rules:
    - from:
        - source:
            principals:
              - cluster.local/ns/hyrule-castle/sa/frappe-suite-frontend
      to:
        - operation:
            ports: ["8000"]
