apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-twenty-to-twenty-postgres
spec:
  selector:
    matchLabels:
      app: twenty-postgres
  action: ALLOW
  rules:
    - from:
        - source:
            principals:
              - cluster.local/ns/hyrule-castle/sa/twenty
      to:
        - operation:
            ports: ["5432"]
