apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-erpnext-frontend-to-erpnext-websocket
spec:
  selector:
    matchLabels:
      app: erpnext-websocket
  action: ALLOW
  rules:
    - from:
        - source:
            principals:
              - cluster.local/ns/hyrule-castle/sa/erpnext-frontend
      to:
        - operation:
            ports: ["9000"]
