apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-harbor-proxy-cache-to-harbor
spec:
  selector:
    matchLabels:
      app: harbor
      component: nginx
  action: ALLOW
  rules:
    - from:
        - source:
            principals:
              - "cluster.local/ns/hyrule-castle/sa/harbor-proxy-cache-proxy"
      to:
        - operation:
            ports: ["8080"]
