apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-opnform-client-to-opnform-ingress
  namespace: hyrule-castle
spec:
  selector:
    matchLabels:
      app: opnform-ingress
  action: ALLOW
  rules:
    - from:
        - source:
            principals:
              - cluster.local/ns/hyrule-castle/sa/opnform-client
      to:
        - operation:
            ports: ["80"]
