apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-calcom-postgres-replication
spec:
  selector:
    matchLabels:
      cnpg.io/cluster: calcom-postgres
  action: ALLOW
  rules:
    - from:
        - source:
            principals:
              - cluster.local/ns/hyrule-castle/sa/calcom-postgres
      to:
        - operation:
            ports: ["5432"]
