apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-osticket-app-to-osticket-mariadb
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: osticket-mariadb
  action: ALLOW
  rules:
    - from:
        - source:
            principals:
              - cluster.local/ns/hyrule-castle/sa/osticket-app
      to:
        - operation:
            ports: ["3306"]
