apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-harbor-redis-intra-cluster
spec:
  selector:
    matchLabels:
      app: harbor-redis
  action: ALLOW
  rules:
    - from:
        - source:
            principals:
              - cluster.local/ns/hyrule-castle/sa/harbor-redis
      to:
        - operation:
            ports: ["6379"]
