{
 "title": "docker container & OS node(node_exporter, cadvisor)",
 "description": "中文 docker 容器 cadvisor 和主机指标面板",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "JOB",
    "query": {
     "query": "label_values(cadvisor_version_info{},job)"
    }
   },
   {
    "name": "instance",
    "label": "主机(instance)",
    "query": {
     "query": "label_values(cadvisor_version_info{},instance)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "主机指标 ( 可绑定到主机，需要 node-exporter 的 instance 标签值与 cadvisor 的 instance 标签值相同 )",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "1m 负载",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_load1{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "5m 负载",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_load5{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "系统正常运行时间",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "正在运行的容器数量",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(container_last_seen{instance=\"$instance\", name=~\".+\"})"
    }
   ]
  },
  {
   "title": "CPU 使用率",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg(rate(node_cpu_seconds_total{instance=\"$instance\", mode='idle'}[1m])) by (server) * 100)"
    }
   ]
  },
  {
   "title": "内存使用率",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{instance=\"$instance\"} - node_memory_MemAvailable_bytes{instance=\"$instance\"}) / node_memory_MemTotal_bytes{instance=\"$instance\"} * 100"
    }
   ]
  },
  {
   "title": "swap 使用率",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=\"$instance\"} - node_memory_SwapFree_bytes{instance=\"$instance\"}) / node_memory_SwapTotal_bytes{instance=\"$instance\"} * 100"
    }
   ]
  },
  {
   "title": "15m 负载",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_load15{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "主机 CPU 使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "100 - (avg(rate(node_cpu_seconds_total{instance=\"$instance\", mode='idle'}[$__rate_interval])) by (server) * 100)",
     "legendFormat": "总使用率"
    },
    {
     "expr": "(avg(rate(node_cpu_seconds_total{instance=\"$instance\", mode=\"user\"}[$__rate_interval])) by (server) * 100)",
     "legendFormat": "user"
    },
    {
     "expr": "(avg(rate(node_cpu_seconds_total{instance=\"$instance\", mode=\"system\"}[$__rate_interval])) by (server) * 100)",
     "legendFormat": "system"
    },
    {
     "expr": "(avg(rate(node_cpu_seconds_total{instance=\"$instance\", mode=\"steal\"}[$__rate_interval])) by (server) * 100)",
     "legendFormat": "steal"
    },
    {
     "expr": "(avg(rate(node_cpu_seconds_total{instance=\"$instance\", mode=\"softirq\"}[$__rate_interval])) by (server) * 100)",
     "legendFormat": "softirq"
    },
    {
     "expr": "(avg(rate(node_cpu_seconds_total{instance=\"$instance\", mode=\"nice\"}[$__rate_interval])) by (server) * 100)",
     "legendFormat": "nice"
    },
    {
     "expr": "(avg(rate(node_cpu_seconds_total{instance=\"$instance\", mode=\"irq\"}[$__rate_interval])) by (server) * 100)",
     "legendFormat": "irq"
    },
    {
     "expr": "(avg(rate(node_cpu_seconds_total{instance=\"$instance\", mode=\"iowait\"}[$__rate_interval])) by (server) * 100)",
     "legendFormat": "iowait"
    },
    {
     "expr": "(avg(rate(node_cpu_seconds_total{instance=\"$instance\", mode=\"idle\"}[$__rate_interval])) by (server) * 100)",
     "legendFormat": "idle"
    }
   ]
  },
  {
   "title": "主机内存使用量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$instance\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$instance\"} - node_memory_MemAvailable_bytes{instance=\"$instance\"}",
     "legendFormat": "Usage"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{instance=\"$instance\"}",
     "legendFormat": "Availavle"
    }
   ]
  },
  {
   "title": "网络流量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{instance=\"$instance\", device=~\"eth.*|ens.*\"}[$__rate_interval])",
     "legendFormat": "{{device}}_Receive"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{instance=\"$instance\", device=~\"eth.*|ens.*\"}[$__rate_interval])",
     "legendFormat": "{{device}}_Transmit"
    }
   ]
  },
  {
   "title": "磁盘每秒 I/O 容量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{instance=\"$instance\", device!~\"dm.*\"}[$__rate_interval])",
     "legendFormat": "{{device}}_read"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{instance=\"$instance\", device!~\"dm.*\"}[$__rate_interval])",
     "legendFormat": "{{device}}_written"
    }
   ]
  },
  {
   "title": "磁盘信息",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"$instance\", fstype=~\"xfs|ext(3|4)|nfs.*|vfat\"}"
    },
    {
     "expr": "node_filesystem_free_bytes{instance=\"$instance\", fstype=~\"xfs|ext(3|4)|nfs.*|vfat\"}"
    },
    {
     "expr": "node_filesystem_files_free{instance=\"$instance\", fstype=~\"xfs|ext(3|4)|nfs.*|vfat\"}"
    }
   ]
  },
  { "title": "容器指标", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "容器 CPU 使用率",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{instance=\"$instance\", name=~'.+'}[$__rate_interval]) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "容器网络流量",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{instance=\"$instance\", name=~\".+\", interface=~\"eth.*|ens.*\"}[$__rate_interval])",
     "legendFormat": "{{name}}_{{interface}}_Receive"
    },
    {
     "expr": "rate(container_network_transmit_bytes_total{instance=\"$instance\", name=~\".+\", interface=~\"eth.*|ens.*\"}[$__rate_interval])",
     "legendFormat": "{{name}}_{{interface}}_Transmit"
    }
   ]
  },
  {
   "title": "容器内存使用量",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{instance=\"$instance\", name=~\".+\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "容器详细信息", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "容器详细信息",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{instance=\"$instance\", name=~\".+\"}[$__rate_interval]) * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "container_spec_memory_limit_bytes{instance=\"$instance\", name=~\".+\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "container_memory_usage_bytes{instance=\"$instance\", name=~\".+\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(container_oom_events_total{instance=\"$instance\", name=~\".+\"}[24h])",
     "legendFormat": "__auto"
    },
    {
     "expr": "container_last_seen{nstance=\"$instance\", container_label_com_docker_compose_project=~\".*\", name=~\".+\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}