{
 "title": "Docker - Node & Container stats",
 "description": "Docker stats by Ron Pool ",
 "tags": [
  "prometheus",
  "docker",
  "linux"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "containers",
    "label": "Containers",
    "query": {
     "query": "label_values(docker_container_running_state{host=~ \"$host\"}, name)"
    }
   },
   {
    "name": "host",
    "label": "host",
    "query": {
     "query": "label_values(docker_containers,host)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Platform", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Containers per host",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "docker_containers", "legendFormat": "{{alias}}" }
   ]
  },
  {
   "title": "Total Containers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "\r\nsum (docker_containers)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total hosts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 11, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "\r\ncount(docker_containers)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Cores",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 13, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "\r\ncount(docker_container_cpu_capacity_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total disk action",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 1 },
   "targets": [
    {
     "expr": "avg(rate(docker_container_disk_read_bytes[5m]))",
     "legendFormat": "Disk read"
    },
    {
     "expr": "avg(- rate(docker_container_disk_write_bytes[5m]))",
     "legendFormat": "Disk write"
    }
   ]
  },
  {
   "title": "Host",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true
  },
  {
   "title": "Containers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "docker_containers{host=\"$host\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total diskspace",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 2, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{host=\"$host\",fstype=\"ext4\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Free diskspace",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_avail_bytes {host=~'$host',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage by container(s)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 14, "x": 10, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(node_cpu_seconds_total{host=\"$host\",mode=\"idle\"}[5m]) /10",
     "legendFormat": "Core: {{cpu}}"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Status",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "node_time- docker_container_start_time_seconds{host=~\"$host\", name=~\"$containers\"}"
    },
    {
     "expr": "sum(docker_container_running_state{host =~ \"$host\", name =~ \"$containers\"}) without (__name__)"
    },
    {
     "expr": "sum(increase(docker_container_restart_count{host =~ \"$host\", name =~ \"$containers\"}[$__range])) without (__name__)"
    }
   ]
  },
  {
   "title": "Container",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true
  },
  {
   "title": "CPU %",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(increase(docker_container_cpu_used_total{host =~ \"$host\", name =~ \"$containers\"}[30s]) / increase(docker_container_cpu_capacity_total[30s])) > 0 or (increase(docker_container_cpu_used_total{host =~ \"$host\", name =~ \"$containers\"}[1m]) / increase(docker_container_cpu_capacity_total[1m])) > 0 or (increase(docker_container_cpu_used_total{host =~ \"$host\", name =~ \"$containers\"}[3m]) / increase(docker_container_cpu_capacity_total[3m])) > 0 or (increase(docker_container_cpu_used_total{host =~ \"$host\", name =~ \"$containers\"}[5m]) / increase(docker_container_cpu_capacity_total[5m]))",
     "legendFormat": "{{host}} / {{name}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "docker_container_memory_used_bytes{host =~ \"$host\", name=~ \"$containers\"}",
     "legendFormat": "{{host}} / {{name}}"
    }
   ]
  },
  {
   "title": "Network I/O (+transmit, -receive)",
   "type": "timeseries",
   "description": "Receive displayed as negative for easy differentiation on single panel",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(docker_container_network_in_bytes{host =~ \"$host\", name =~ \"$containers\"}[1m]) * -8",
     "legendFormat": "{{host}} / {{name}} receive"
    },
    {
     "expr": "rate(docker_container_network_out_bytes{host =~ \"$host\", name =~ \"$containers\"}[1m]) * 8",
     "legendFormat": "{{host}} / {{name}} transmit"
    },
    { "expr": "vector(0)", "legendFormat": "Zero point reference" }
   ]
  },
  {
   "title": "Disk I/O (+write, -read)",
   "type": "timeseries",
   "description": "Read displayed as negative for easy differentiation on single panel",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "-rate(docker_container_disk_read_bytes{host =~ \"$host\", name =~ \"$containers\"}[1m])",
     "legendFormat": "{{host}} / {{name}} read"
    },
    {
     "expr": "rate(docker_container_disk_write_bytes{host =~ \"$host\", name =~ \"$containers\"}[1m])",
     "legendFormat": "{{host}} / {{name}} write"
    },
    { "expr": "vector(0)", "legendFormat": "Zero point reference" }
   ]
  }
 ]
}