{
 "title": "Sui Validator Metrics Container in Docker and System Monitoring",
 "description": "Sui Validator Metrics cAdvisor + Prometheus + Node Exporter.",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "30s,1m,2m,3m,5m,7m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "server",
    "label": "Node",
    "query": {
     "query": "label_values(node_boot_time_seconds, instance)"
    }
   },
   {
    "name": "node",
    "label": "Host:",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\"}, instance)"
    }
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Validator Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Epoch",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "current_epoch", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Voting Right",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "current_voting_right", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "uptime{version=\"0.31.0-a63f425b9\"} / 3600",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Certificates Created",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "certificates_created", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Certificates created",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 3, "y": 5 },
   "targets": [
    { "expr": "certificates_created", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Certificates Created per 1m",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 13, "x": 11, "y": 5 },
   "targets": [
    { "expr": "rate(certificates_created[1m])", "legendFormat": "amount" }
   ]
  },
  {
   "title": "Rounds",
   "type": "bargauge",
   "description": "last_committed_round The most recent round that has been committed from consensus\n\ncurrent_round Current round the node will propose",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "last_committed_round", "legendFormat": "{{__name__}}" },
    { "expr": "current_round", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Highest Received Round",
   "type": "timeseries",
   "description": "highest_received_round Highest round received by the primary",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "highest_received_round{source=\"own\"}",
     "legendFormat": "received own"
    },
    {
     "expr": "highest_received_round{source=\"other\"}",
     "legendFormat": "received other"
    }
   ]
  },
  {
   "title": "Highest checkpoint",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "highest_known_checkpoint", "legendFormat": "known" },
    { "expr": "highest_synced_checkpoint", "legendFormat": "synced" },
    { "expr": "highest_verified_checkpoint", "legendFormat": "verified" }
   ]
  },
  {
   "title": "Executed Checkpoints",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 14, "x": 10, "y": 15 },
   "targets": [
    { "expr": "last_executed_checkpoint", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Host",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "dtdhms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "time() - node_boot_time_seconds{instance=\"$server\",job=\"$job\"}"
      }
     ]
    },
    {
     "title": "Containers",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(rate(container_last_seen{name=~\".+\"}[$interval]))"
      }
     ]
    },
    {
     "title": "Disk space",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "min((node_filesystem_size_bytes{fstype=~\"xfs|ext4\",instance=~\"$server\"} - node_filesystem_free_bytes{fstype=~\"xfs|ext4\",instance=~\"$server\"} )/ node_filesystem_size_bytes{fstype=~\"xfs|ext4\",instance=~\"$server\"})"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "((node_memory_MemTotal_bytes{instance=~\"$server\"} - node_memory_MemAvailable_bytes{instance=~\"$server\"}) / node_memory_MemTotal_bytes{instance=~\"$server\"}) * 100"
      }
     ]
    },
    {
     "title": "Swap",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(node_memory_SwapTotal_bytes{instance=~\"$server\"} - node_memory_SwapFree_bytes{instance=~\"$server\"})"
      }
     ]
    },
    {
     "title": "Load",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "node_load1{instance=~\"$server\"} / count by(job, instance)(count by(job, instance, cpu)(node_cpu_seconds_total{instance=~\"$server\"}))"
      }
     ]
    },
    {
     "title": "Network Traffic",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_bytes_total{id=\"/\"}[$interval])) by (id)",
       "legendFormat": "RECEIVED"
      },
      {
       "expr": "- sum(rate(container_network_transmit_bytes_total{id=\"/\"}[$interval])) by (id)",
       "legendFormat": "SENT"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 4, "x": 4, "y": 25 },
     "targets": [
      {
       "expr": "sum(rate(process_cpu_seconds_total[$interval])) * 100",
       "legendFormat": "host"
      }
     ]
    },
    {
     "title": "Disk I/O",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 4, "x": 8, "y": 25 },
     "targets": [
      {
       "expr": "-sum(rate(node_disk_read_bytes_total[$interval])) by (device)",
       "legendFormat": "OUT on /{{device}}"
      },
      {
       "expr": "sum(rate(node_disk_written_bytes_total[$interval])) by (device)",
       "legendFormat": "IN on /{{device}}"
      }
     ]
    },
    {
     "title": "RootFS Total",
     "type": "stat",
     "description": "Total RootFS",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(node_filesystem_size_bytes{instance=\"$server\"})\n"
      }
     ]
    },
    {
     "title": "CPU Cores",
     "type": "stat",
     "description": "Total number of CPU cores",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(count(node_cpu_seconds_total{instance=\"$server\",job=\"$job\"}) by (cpu))"
      }
     ]
    },
    {
     "title": "Disk Space Used",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 20, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "node_filesystem_size_bytes{instance=\"$node\",job=\"$job\",device!~'rootfs'} - node_filesystem_avail_bytes{instance=\"$node\",job=\"$job\",device!~'rootfs'}",
       "legendFormat": "{{mountpoint}}"
      }
     ]
    },
    {
     "title": "RAM Total",
     "type": "stat",
     "description": "Total RAM",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{instance=\"$server\",job=\"$job\"}"
      }
     ]
    },
    {
     "title": "SWAP Total",
     "type": "stat",
     "description": "Total SWAP",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_memory_SwapTotal_bytes{instance=\"$server\",job=\"$job\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Containers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "FS Usage per Container",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(container_fs_usage_bytes{name=~\".+\"}) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "CPU Usage per Container",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\".+\"}[$interval])) by (name) * 100",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Memory Usage per Container",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
     "targets": [
      {
       "expr": "sum(container_memory_rss{name=~\".+\"}) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Memory Swap per Container",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
     "targets": [
      {
       "expr": "sum(container_memory_swap{name=~\".+\"}) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Received Network Traffic per Container",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_bytes_total{name=~\".+\"}[$interval])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Sent Network Traffic per Container",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
     "targets": [
      {
       "expr": "sum(rate(container_network_transmit_bytes_total{name=~\".+\"}[$interval])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  }
 ]
}